### ISSUE TITLE
Adding Splash/Launch Screen

### ISSUE THREAD

**Issue by cedricbahirwe** [cedricbahirwe/dialer-android#37]
Building Splash/Launch Screen of the app using the right technologies (not hacky, less friction, easy to maintain)

Resources:
1. By @esthcarelle : https://github.com/cedricbahirwe/dialer-android/issues/37#issuecomment-1747190241

Assets: [App + Company Icons](https://github.com/cedricbahirwe/dialer-android/files/12821262/Archive.zip)

<img src="https://github.com/cedricbahirwe/dialer-android/assets/49038614/c08a20b4-7351-4edc-93ed-93acfd6d12bb" alt="iPhone 15" width="400" height="890">

**Comment by cedricbahirwe** [comment]
The App + Company Icons : [Archive.zip](https://github.com/cedricbahirwe/dialer-android/files/12781211/Archive.zip)

**Comment by esthcarelle** [comment]
@cedricbahirwe are you using the splash screen library?

**Comment by esthcarelle** [comment]
and what do you mean with less friction? I can only see an image, could you add a video?

**Comment by cedricbahirwe** [comment]
> @cedricbahirwe are you using the splash screen library?

No, I meant a launch screen, (just icons, no animations whatsoever )

**Comment by cedricbahirwe** [comment]
> and what do you mean with less friction? I can only see an image, could you add a video?

I meant, a way to have the launch screen without hacking our way in

**Comment by esthcarelle** [comment]
The launch screen is the splash screen right?

**Comment by esthcarelle** [comment]
I do not understand your point can you send me a professional voice note on whatsapp?
Regards

**Comment by esthcarelle** [comment]
Are you using the splash screen library or are you creating the splash screen yourself?

**Comment by cedricbahirwe** [comment]
I’m planning to create the splash myself…

**Comment by esthcarelle** [comment]
this can also work right https://developer.android.com/develop/ui/views/launch/splash-screen?

**Comment by esthcarelle** [comment]
@cedricbahirwe could you please add a red png icon in the folder you provided or an SVG icon?

**Comment by cedricbahirwe** [comment]
> @cedricbahirwe could you please add a red png icon in the folder you provided or an SVG icon?

@esthcarelle , I have updated the archive with the red icon, please not that I could not find an svg

**Comment by esthcarelle** [comment]
@cedricbahirwe as you can see with this attached screenshot the branding name has to be an image yet for us we have the abc logo + "powered by" text so with the solution we decided to go with there are 2 possible solutions:
1.If we decide to keep using the splash api which is the much faster way both on implementation side and performance, You might combine the text and the abc logo into one image(png)
2. We decide to go the old way(we create the splash activity and we build the screen ourselves
![Screenshot from 2023-10-06 10-21-02](https://github.com/cedricbahirwe/dialer-android/assets/52702726/8d56a319-a811-455c-9612-8afbbd531dde)

**Comment by cedricbahirwe** [comment]
Would providing "powered by + logo" as a png work ??

**Comment by esthcarelle** [comment]
Thanks

**Comment by esthcarelle** [comment]
Aspect ratio of the branding image should be 5:2. For example, if the width is 200, then the height should be 80(200/2,5).The one you provided looks squizzed
[device-2023-10-06-124255.webm](https://github.com/cedricbahirwe/dialer-android/assets/52702726/50437e7f-327b-4409-9074-b40029714194)

**Comment by esthcarelle** [comment]
And for the icon
Icon needs to be square(aspect ratio — 1:1).
Visible part of the icon will be only <icon size>/1.5.

**Comment by cedricbahirwe** [comment]
which dimension do you need for the brand? (Width + height)

**Comment by cedricbahirwe** [comment]
By the way, I'm using https://www.remove.bg/ to remove background once I crop the screenshot I shared

**Comment by esthcarelle** [comment]
@cedricbahirwe 200dp width and 80dp height

**Comment by cedricbahirwe** [comment]
![200x80](https://github.com/cedricbahirwe/dialer-android/assets/49038614/3026a239-7407-4c36-b3c3-c81399b2aaad)

**Comment by cedricbahirwe** [comment]
Try this and let me know, please, then I can provide the red color

![200x80-removebg-preview](https://github.com/cedricbahirwe/dialer-android/assets/49038614/be08a0d8-81d4-4ed4-a569-73f8a268f1ea)

**Comment by cedricbahirwe** [comment]
The app icon is sqaured( 350x350), what is missing?

**Comment by cedricbahirwe** [comment]
This is 400 by 400 with the icon smaler
![400x400](https://github.com/cedricbahirwe/dialer-android/assets/49038614/eb387a49-8901-48e6-9775-1b3dd9d57e30)
