### ISSUE TITLE
Implement App Icon

### ISSUE THREAD

**Issue by cedricbahirwe** [cedricbahirwe/dialer-android#45]
- Display the App Icon on the device
- Make sure the icon is not cropped or shrinked

**Comment by salmanA169** [comment]
assign this task to me @cedricbahirwe

**Comment by cedricbahirwe** [comment]
Thanks  @salmanA169  for your interest, I'll assign you this issue.

You can start by checking this old PR https://github.com/cedricbahirwe/dialer-android/pull/4  (might find some useful icons), as well as this old [commit](https://github.com/cedricbahirwe/dialer-android/commit/968f2ddb203948b5208c3b7e949537f9cdb80a5d)

Almost Everything in this project is made by us (icons, png, etc), so please don't hesitate to ask If you are missing something  or if you have any questions

**Comment by cedricbahirwe** [comment]
Here are the icons @cedricbahirwe 

[AppIcons.zip](https://github.com/cedricbahirwe/dialer-android/files/13224878/AppIcons.zip)
